# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 523ede3045ace67c90d79e2181a5cc7a1b507d59c9b479c585bc281fbf595a07dfb0681b62c99ea95f1d459596fd71e9c74733b9bd07cf6a3191c8af77f28959

test:
  secret_key_base: a45278e5325fd07b89c99996db587f2a4a6a1cbff7c0741938859ad18ba99e9c64ec6acf22f71a40fc1e386844a31b78355cff7bdd2f9d190e95304e0bf120ed

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
